language: java

addons:
  sonarcloud:
    organization: "caroleastier-github"


script:
   # JaCoCo is used to have code coverage, the agent has to be activated
    - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=Analyze "ipi-java-350-ex" b

